# Generated by Django 3.1.1 on 2020-09-21 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_app', '0005_auto_20200921_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.FloatField()),
                ('product_unit', models.CharField(max_length=100)),
                ('product_price_per_unit', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('issue_date', models.DateField(default=datetime.datetime.now)),
                ('due_date', models.DateField()),
                ('vendor_unique_code', models.CharField(blank=True, max_length=100)),
                ('company_a_proc_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('vendor_unique_code', models.CharField(max_length=100)),
                ('offered_price_per_unit', models.FloatField()),
                ('offered_quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('status', models.CharField(default='Ongoing', max_length=100)),
                ('proc_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.procurementoffermodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendor_app.proposalmodel')),
            ],
        ),
    ]
