# Generated by Django 3.1.1 on 2020-09-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0005_auto_20200921_0630'),
        ('procurement_app', '0002_remove_acceptedoffermodel_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOfferDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('vendor_unique_code', models.CharField(max_length=100)),
                ('offered_price_per_unit', models.FloatField()),
                ('offered_quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('status', models.CharField(default='Ongoing', max_length=100)),
                ('proc_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.procurementoffermodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.proposalmodel')),
            ],
        ),
    ]
