# Generated by Django 3.1.1 on 2020-09-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0002_auto_20200920_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementoffermodel',
            name='product_unit',
            field=models.CharField(default='Pieces', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procurementoffermodel',
            name='issue_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='procurementoffermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='procurementoffermodel',
            name='vendor_unique_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
