# Generated by Django 3.1.1 on 2020-09-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0003_acceptedofferdetailsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedofferdetailsmodel',
            name='offered_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='acceptedofferdetailsmodel',
            name='offered_quantity',
        ),
    ]
