# Generated by Django 3.1.1 on 2020-09-21 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0004_procurementoffermodel_company_a_proc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementoffermodel',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
