# Generated by Django 3.1.1 on 2020-09-21 10:31

from django.db import migrations, models
import procurement_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0004_auto_20200921_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedofferdetailsmodel',
            name='attachments',
            field=models.FileField(blank=True, upload_to=procurement_app.models.payment_attachment_path),
        ),
        migrations.AddField(
            model_name='acceptedofferdetailsmodel',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='acceptedofferdetailsmodel',
            name='paid_using',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='AcceptedOfferModel',
        ),
    ]
