# Generated by Django 3.1.1 on 2020-09-21 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0005_auto_20200921_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedofferdetailsmodel',
            name='paid_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
