# Generated by Django 3.1.1 on 2020-09-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0006_acceptedofferdetailsmodel_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedofferdetailsmodel',
            name='paid_on',
            field=models.DateField(blank=True),
        ),
    ]
