# Generated by Django 3.1.1 on 2020-09-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0007_auto_20200921_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedofferdetailsmodel',
            name='paid_on',
        ),
    ]
