# Generated by Django 3.1.1 on 2020-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proposalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.CharField(max_length=100)),
                ('vendor_mob', models.CharField(max_length=100)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_quantity', models.CharField(max_length=100)),
                ('vendor_price', models.CharField(max_length=100)),
                ('vendor_info', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
