# Generated by Django 3.1.1 on 2020-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmodel',
            name='proposal_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
