# Generated by Django 3.1.1 on 2020-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_proposalmodel_proposal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='vendor_email',
            field=models.EmailField(max_length=100),
        ),
    ]
