# Generated by Django 3.1.1 on 2020-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_auto_20200920_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='vendor_price',
            field=models.FloatField(),
        ),
    ]
