# Generated by Django 3.1.1 on 2020-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_A_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyainventorymodel',
            name='product_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
