# Generated by Django 3.1.1 on 2020-09-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_A_app', '0002_companyainventorymodel_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyainventorymodel',
            name='product_id',
        ),
    ]
